routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\Front\FrontuserController;
use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\CheckoutController;
use App\Http\Controllers\Front\WishlistController;
use App\Http\Controllers\Front\UserController;
use App\Http\Controllers\Front\RatingController;
use App\Http\Controllers\Admin\DashboardController;
use App\Models\Clients;
use App\Models\Category;
use App\Models\Products;
use App\Models\Rating;
use App\Models\Cart;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/', function () {
   //return view('welcome');
//});
Route::get('/', [FrontuserController::class, 'index']);
Route::get('category', [FrontuserController::class, 'category']);
Route::get('viewcategory/{slug}', [FrontuserController::class, 'viewcategory']);
Route::get('viewproduct/{cate_slug}/{prod_slug}', [FrontuserController::class, 'productview']);
Route::get('product-list', [FrontuserController::class, 'productlistajax']);
Route::post('searchproduct', [FrontuserController::class,'searchProduct']);

Route::post('add-to-cart', [CartController::class, 'add']);
Route::get('/cartview', [CartController::class, 'cartfunction']);
Route::get('delete-cart-item', [CartController::class, 'deleteproduct']);
Route::get('change-total', [CartController::class, 'updatecart']);
Route::get('checkout', [CheckoutController::class, 'index']);
Route::get('place_order', [CheckoutController::class, 'placeorder']);
Route::get('ordersview', [UserController::class, 'index']);
Route::get('view-order/{id}', [UserController::class,'show']);
Route::get('wishlist', [WishlistController::class,'index']);
Route::post('add-to-wishlist', [WishlistController::class,'add']);
Route::post('remove-wishlist-item', [WishlistController::class,'deleteitem']);
Route::get('load-cart-data', [CartController::class, 'cartcount']);
Route::get('load-wishlist-data',[WishlistController::class,'loadwishlist']);
////Route::get('dashboard',[DashboardController::class , 'index']);
//Route::get('dashboard',[DashboardController::class , 'user']);
Route::post('add-rating',[RatingController::class , 'add']);


Route::get('/dashboard', function () {
  return view('front.dashboard');
})->middleware(['front'])->name('dashboard');
require __DIR__.'/front_auth.php';




// Admin routes
Route::get('/admin/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('admin.dashboard');

require __DIR__.'/auth.php';



Route::namespace('App\Http\Controllers\Admin')->name('admin.')->prefix('admin')
    ->group(function(){
      Route::resource('roles','RoleController');
      Route::resource('permissions','PermissionController');
      Route::resource('users','UserController');
      Route::resource('posts','PostController');
      Route::resource('products','ProductsController');
      Route::resource('category','CategoryController'); 
      Route::resource('orders','OrderController'); 
      Route::resource('frontusers','DashboardController'); 
         
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
   
    
        use HasFactory;
        public $timestamps =false;
        protected $table = 'category';
        protected $fillable = [
       'name',
       'slug',
       'description',
      'status',
        'popular',
       'meta_title',
       'meta_descrip',
       'meta_keywords',
       'image_cat'];
     
    
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Models\Category;
use DB;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{    


  

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('setting.categories.newcategory');
    }
   
    
    public function store(Request $req)
    {
      
    $Category  = new Category ;
    $Category ->name = $req->name;
    $Category ->slug = $req->slug;
    $Category ->description = $req->description;
    $Category ->status = $req->status == TRUE ? '1':'0';
    $Category ->popular = $req->popular== TRUE ? '1':'0';
    $Category ->meta_title = $req->meta_title;
    $Category ->meta_descrip = $req->meta_descrip;
    $Category ->meta_keywords = $req->meta_keywords;
    
    $req->file('image_cat')->move(
        public_path('storage/images/'),
        $req->file('image_cat')->getClientOriginalName()
    );
    $Category ->image_cat=$req->file('image_cat')->getClientOriginalName();
    $Category ->save();
     
    return redirect()->back()->withSuccess('Category created !!!');
    }
    public function index()
    {
        $data= Category::all();
        return view('setting.categories.index',compact('data'));
    }
   
    public function destroy(Category $id){
        $Category = Category::find($id); 
        $Category->delete(); 
        return redirect()->back()->withSuccess('Category deleted !!!');
    }

    public function edit($id){ 
        $cat =  Category::find($id);
        return view('setting.categories.edit',compact('cat'));  
    }

    public function update(Request $req,$id){
        $name = $req->input('name');
        $slug = $req->input('slug');
        $description = $req->input('description');       
        $status = $req->input('status')== TRUE ? '1':'0';
        $popular = $req->input('popular')== TRUE ? '1':'0';
        $meta_title = $req->input('meta_title');
        $meta_descrip = $req->input('meta_descrip');
        $meta_keywords = $req->input('meta_keywords');
        $item= Category::find($id);
        $path = '';
        if (request()->hasFile('image_cat')){
            request()->file('image_cat')->move(
                public_path('storage/images'),
                request()->file('image_cat')->getClientOriginalName()
            );
            $path = request()->file('image_cat')->getClientOriginalName();
        }else{
            $path = $item->image_cat;
        }
        $item->update([
                 'name' => $name,
                 'slug' => $slug,
                 'description' => $description,
                 'status' => $status== TRUE ? '1':'0',
                 'popular' => $popular== TRUE ? '1':'0',
                 'meta_title' => $meta_title,
                 'meta_descrip' => $meta_descrip,
                 'meta_keywords' => $meta_keywords,
                 'image_cat' => $path,
             ]);
        return redirect()->back()->withSuccess('Category updated !!!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/setting/categories/edit.blade.php
<x-app-layout>
    <div>
         <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
             <div class="container mx-auto px-6 py-1 pb-16">
               <div class="bg-white shadow-md rounded my-6 p-5">
                 <form method="POST" action="{{ route('admin.category.update',$cat->id)}}" enctype="multipart/form-data">
                   @csrf
                   @method('put')
                   <div class="flex flex-col space-y-2">
                     <label for="name" class="text-gray-700 select-none font-medium"> Name</label>
                     <input id="name" type="text" name="name" value="{{$cat['name']}}"
                       placeholder="Enter name" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
         
                 <div class="flex flex-col space-y-2">
                     <label for="slug" class="text-gray-700 select-none font-medium">Slug</label>
                     <input id="slug" type="text" name="slug"value="{{$cat['slug']}}"
                       placeholder="Enter slug" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
                 <div class="flex flex-col space-y-2">
                    <label for="description" class="text-gray-700 select-none font-medium">Description</label>
                    <input id="description" type="text" name="description"value=" {{$cat['description']}}"
                      placeholder="Enter description" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                <h3 class="flex flex-col space-y-2 ">Status</h3>
                <div class="grid grid-cols-3 gap-4">
                      <div class="flex flex-col justify-cente">
                          <div class="flex flex-col">
                              <label class="inline-flex items-center mt-3">
                                  <input type="checkbox" {{$cat->status== "1" ? 'checked': ''}} class="form-checkbox " name="status" 
                                  ><span class="ml-2 text-gray-700"></span>
                              </label>
                          </div>
                      </div>
                </div>
                <h3 class="flex flex-col space-y-2 ">Popular</h3>
                 <div class="grid grid-cols-1 gap-2">
                       <div class="flex flex-col justify-cente">
                           <div class="flex flex-col">
                               <label class="inline-flex items-center mt-3">
                                   <input type="checkbox" {{$cat->popular== '1' ? 'checked' : ''}}class="form-checkbox " name="popular" 
                                   ><span class="ml-2 text-gray-700"></span>
                               </label>
                           </div>
                       </div>
                 </div>
                 <div class="flex flex-col space-y-2">
                     <label for="meta_title" class="text-gray-700 select-none font-medium">Meta title</label>
                     <input id="meta_title" type="text" name="meta_title" value="{{$cat['meta_title']}}"
                       placeholder="Enter meta title" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
                 <div class="flex flex-col space-y-2">
                    <label for="meta_descrip" class="text-gray-700 select-none font-medium">Meta description</label>
                    <input id="meta_descrip" type="text" name="meta_descrip" value="{{$cat['meta_descrip']}}"
                      placeholder="Enter password" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                <div class="flex flex-col space-y-2">
                    <label for="meta_keywords" class="text-gray-700 select-none font-medium">Meta keywords</label>
                    <input id="meta_keywords" type="text" name="meta_keywords" value="{{$cat['meta_keywords']}}"
                      placeholder="Enter password" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                 
  
                 <div class="form-group" style="margin-right: 3rem;">
                    <label for="image_cat">Image</label>
                    <input type="file" class="form-control" id="exampleInputEmail1"name="image_cat" placeholder="Enter image cat">
                   
                  </div>
 
                 
                 <div class="text-center mt-16 mb-16">
                   <button type="ADD Category" class="bg-blue-500 text-white font-bold px-5 py-1 rounded focus:outline-none shadow hover:bg-blue-500 transition-colors ">Submit</button>
                 </div>
               </div>
 
              
             </div>
         </main>
     </div>
 </div>
 </x-app-layout>

resources/views/setting/categories/index.blade.php
<x-app-layout>
    <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
        <div class="container mx-auto px-6 py-2">
            <div class="text-right">
              
                <a href="{{route('admin.category.create')}}" class="bg-blue-500 text-white font-bold px-5 py-1 rounded focus:outline-none shadow hover:bg-blue-500 transition-colors ">New Category</a>
             
            </div>
  
          <div class="bg-white shadow-md rounded my-6">
            <table class="text-left w-full border-collapse">
              <thead>
                <tr>
                  <th class="py-4 px-6 " >ID</th>
                  <th class="py-4 px-6 ">Name</th>
                  <th class="py-4 px-6 ">Description</th>
                  <th class="py-4 px-6 ">Image</th>
                  <th class="py-4 px-6 ">Actions</th>
                </tr>
              </thead>
              <tbody>
                  @foreach($data as $item)
                  <tr class="hover:bg-grey-lighter">
                    <td class="py-4 px-6 border-b border-grey-light">{{$item->id}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->description}}</td>
                    <td>
                        <div class="image" >
                        <img src="{{asset('storage/images/'.$item->image_cat)}}"  class="" alt="User Image" height= "70px" width="70px">
                        </div>
                    </td>
  
                    <td>
                      <a href="{{route('admin.category.edit',$item->id)}}" class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-green hover:bg-green-dark text-blue-400">Edit</a>
                      
  
                    
                      <form action="{{ route('admin.category.destroy', $item->id) }}" method="POST" class="inline">
                          @csrf
                          @method('delete')
                          <button class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-blue hover:bg-blue-dark text-red-400">Delete</button>
                      </form>
                     
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
        </div>
    </main>
  </div>
  </x-app-layout>
 
     

resources/views/setting/categories/newcategory.blade.php
<x-app-layout>
    <div>
         <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
             <div class="container mx-auto px-6 py-1 pb-16">
               <div class="bg-white shadow-md rounded my-6 p-5">
                 <form method="POST" action="{{ route('admin.category.store')}}" enctype="multipart/form-data">
                   @csrf
                   @method('post')
                   <div class="flex flex-col space-y-2">
                     <label for="name" class="text-gray-700 select-none font-medium"> Name</label>
                     <input id="name" type="text" name="name" 
                       placeholder="Enter name" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
         
                 <div class="flex flex-col space-y-2">
                     <label for="slug" class="text-gray-700 select-none font-medium">Slug</label>
                     <input id="slug" type="text" name="slug"
                       placeholder="Enter slug" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
                 <div class="flex flex-col space-y-2">
                    <label for="description" class="text-gray-700 select-none font-medium">Description</label>
                    <input id="description" type="text" name="description" 
                      placeholder="Enter description" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                <h3 class="flex flex-col space-y-2 ">Status</h3>
                <div class="grid grid-cols-3 gap-4">
                      <div class="flex flex-col justify-cente">
                          <div class="flex flex-col">
                              <label class="inline-flex items-center mt-3">
                                  <input type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" name="status" 
                                  ><span class="ml-2 text-gray-700"></span>
                              </label>
                          </div>
                      </div>
                </div>
                <h3 class="flex flex-col space-y-2 ">Popular</h3>
                 <div class="grid grid-cols-1 gap-2">
                       <div class="flex flex-col justify-cente">
                           <div class="flex flex-col">
                               <label class="inline-flex items-center mt-3">
                                   <input type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" name="popular" 
                                   ><span class="ml-2 text-gray-700"></span>
                               </label>
                           </div>
                       </div>
                 </div>
                 <div class="flex flex-col space-y-2">
                     <label for="meta_title" class="text-gray-700 select-none font-medium">Meta title</label>
                     <input id="meta_title" type="text" name="meta_title" 
                       placeholder="Enter meta title" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                     />
                 </div>
                 <div class="flex flex-col space-y-2">
                    <label for="meta_descrip" class="text-gray-700 select-none font-medium">Meta description</label>
                    <input id="meta_descrip" type="text" name="meta_descrip" 
                      placeholder="Enter password" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                <div class="flex flex-col space-y-2">
                    <label for="meta_keywords" class="text-gray-700 select-none font-medium">Meta keywords</label>
                    <input id="meta_keywords" type="text" name="meta_keywords" 
                      placeholder="Enter password" class="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200"
                    />
                </div>
                 
  
                 <div class="form-group" style="margin-right: 3rem;">
                    <label for="image_cat">Image</label>
                    <input type="file" class="form-control" id="exampleInputEmail1"name="image_cat" placeholder="Enter image cat">
                   
                  </div>
 
                 
                 <div class="text-center mt-16 mb-16">
                   <button type="ADD Category" class="bg-blue-500 text-white font-bold px-5 py-1 rounded focus:outline-none shadow hover:bg-blue-500 transition-colors ">Submit</button>
                 </div>
               </div>
 
              
             </div>
         </main>
     </div>
 </div>
 </x-app-layout>